---
# tasks file for galaxyproject.cvmfs

- name: Set OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Set facts for Galaxy CVMFS config repository, if enabled
  ansible.builtin.set_fact:
    cvmfs_config_repo: "{{ galaxy_cvmfs_config_repo }}"
  when: galaxy_cvmfs_repos_enabled and galaxy_cvmfs_repos_enabled == 'config-repo'

- name: Set facts for Galaxy CVMFS static repositories, if enabled
  ansible.builtin.set_fact:
    cvmfs_keys: "{{ cvmfs_keys + galaxy_cvmfs_keys }}"
    cvmfs_repositories: "{{ cvmfs_repositories + galaxy_cvmfs_repositories }}"
    cvmfs_server_urls: "{{ cvmfs_server_urls + galaxy_cvmfs_server_urls }}"
  when: galaxy_cvmfs_repos_enabled and galaxy_cvmfs_repos_enabled != 'config-repo'

- name: Set facts for CVMFS config repository, if enabled
  ansible.builtin.set_fact:
    cvmfs_keys: "{{ cvmfs_keys + [cvmfs_config_repo.key] }}"
  # In Ansible >= 2.10 this will be | truthy
  when: cvmfs_config_repo | length > 0

- name: Include Client Tasks
  ansible.builtin.include_tasks: client.yml
  when: "'cvmfsclients' in group_names or cvmfs_role == 'client'"

- name: Include Stratum1 Tasks
  ansible.builtin.include_tasks: stratum1.yml
  when: "'cvmfsstratum1servers' in group_names or cvmfs_role == 'stratum1'"

- name: Include Stratum0 Tasks
  ansible.builtin.include_tasks: stratum0.yml
  when: "'cvmfsstratum0servers' in group_names or cvmfs_role == 'stratum0'"

- name: Include localproxy Tasks
  ansible.builtin.include_tasks: localproxy.yml
  when: "'cvmfslocalproxies' in group_names or cvmfs_role == 'localproxy'"
