---
- hosts: galaxy01_educloud
  become: true
  pre_tasks:
    - name: Update and upgrade all yum packages
      yum:
        name: '*'
        state: latest
        exclude: 'slurm*'
    
    - name: Install Environment Groups
      yum:
        name: "@Server"
        state: present

    - name: Install Groups
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - '@Development tools'
        - '@Container Management'
        - '@Headless Management'
        - '@System Tools'
        - epel-release

    - name: Galaxy Dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - acl
        - git
        - make
        - python3
        - python2-psycopg2
        - python3-psycopg2
        - python3-virtualenv
        - bzip2
        - gcc
        - tar
        - mercurial
        - emacs-yaml-mode.noarch

    - name: Install dependencies to compile uWSGI
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - gcc
        - openssl-devel
        - libffi-devel
#----------------------------------------------------------------------
    - name: Install  YUM PosgreSQL PGDG repo rpm
      command: sudo dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm

    - name: Disable present postgresql Module
      become: true
      command:  dnf -qy module disable postgresql

#---------------------------------------------------------------------^
    - name: Install Pipenv
      pip:
        name: pipenv
#    extra_args: --user                                                                                         

    - name: Instal containers modularity appstream with defined stream
      dnf:
        name: '@container-tools:rhel8'
        state: present




