
- type: gxuserhome
  id: userhome
  doc: Get your data from FOX home area
  label: FOX Home Area


- type: gxuserprojects
  id: userprojects
  doc: Get your data from FOX project area
  label: FOX project Area

