---

- hosts: dbservers
  name: Install postgresql
  become: true
  become_user: root
  vars_files:
    - group_vars/env.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: 'acl'
  roles:
     - role: galaxyproject.postgresql
       __postgresql_version_dotless:  ""
     - role: galaxyproject.postgresql_objects
       become: true
       become_user: postgres


- hosts: galaxy01_educloud
  name: Install Galaxy
  become: true
  vars:
      galaxy_diff_mode_verbose: true
      CLIENT_ID: "{{ client_id }}"
      CLIENT_SECRET: "{{ client_secret }}"
  vars_files:
    - group_vars/env.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['acl', 'bzip2', 'git', 'make', 'python3-psycopg2', 'tar', 'python3-virtualenv', 'python3-setuptools', 'python3.11',  'python3-pip.noarch']
    - name: Enable or reenable linger for ec-galaxy user (needed for user systemd setup)
      shell:
            "if [[ $(loginctl list-users | grep 'ec-galaxy') == *2100096* ]]; then loginctl disable-linger ec-galaxy && sleep 5 && loginctl enable-linger ec-galaxy; else loginctl enable-linger ec-galaxy; fi"
      become_user: "{{ galaxy_user_name }}"
    ## In case of root_squash galaxy partition drmaa has to be installed system wide, the venv installed copy will not be usable by
    ## ec-galaxy which escalates to root
    - name: Install drmaa for Python 3
      ansible.builtin.pip:
        name: drmaa
        executable: pip3
    - name: Install the 'Development tools' package group
      ansible.builtin.yum:
         name: "@Development tools"
         state: present
    - name: Create the directory gunicorn
      file:
          path: /gunicorn
          owner: "{{ galaxy_user_name }}"
          group: "{{ galaxy_user_group }}"
          mode: 0755
          state: directory

  roles:
     - role: galaxyproject.miniconda
       become: true
       become_user: "{{ galaxy_user_name }}"
       vars:
           galaxy_conda_create_env: true
           galaxy_conda_env: _galaxy_
           galaxy_conda_env_channels:
               - conda-forge
               - defaults
           galaxy_conda_env_packages:
               - "python={{ galaxy_python_version }}"
               - pip>=23.1
               - virtualenv>=16
     - role: galaxyproject.galaxy
       become: true
       become_user: "{{ galaxy_user_name }}"
      # customized tasks
     - role: lifeportalfox.customized
       become: true
       become_user: "{{ galaxy_user_name }}"
     - role: galaxyproject.nginx
       tags: nginx
       become: yes
       become_user: root
     # - role: slurmdrmaa.galaxy
     #   become: yes
     #   become_user: root
     - role: galaxyproject.gxadmin
     - role: usegalaxy_eu.tpv_auto_lint
       become: true
       become_user: "{{ galaxy_user_name }}"
     - role: galaxyproject.cvmfs
       become: yes
       tags: cvmfs

  post_tasks:
    - name: Change data folder ownership
      become: true
      become_user: root
      command: "{{ item }} chdir={{ galaxy_lifeportal_data_dir }}"
      with_items:
      - "chown -R {{ galaxy_user_name }}:{{ galaxy_user_group }} compiled_templates"
      - "chown -R {{ galaxy_user_name }}:{{ galaxy_user_group }} files"
      - "chown -R {{ galaxy_user_name }}:{{ galaxy_user_group }} jobs_directory"
      - "chown -R {{ galaxy_user_name }}:{{ galaxy_user_group }} tmp"
      - "chown -R {{ galaxy_user_name }}:{{ galaxy_user_group }} tools"
      - "chown {{ galaxy_user_name }}:{{ galaxy_user_group }} scripts"
      changed_when: false

    - name: Change data folder mode
      become: true
      become_user: root
      command: "{{ item }} chdir={{ galaxy_lifeportal_data_dir }}"
      with_items:
      - chmod -R 750 compiled_templates
      - chmod -R 730 files
      - chmod -R g+s files
      - chmod -R 730 jobs_directory
      - chmod -R g+s jobs_directory
      - chmod -R 777 tmp
      - chmod -R g+s tmp
      - chmod -R 750 tools
      - chmod -R 500 scripts
      changed_when: false

    - name: Change ownership to scripts folder
      become: true
      become_user: root
      command: "{{ item }} chdir={{ galaxy_lifeportal_data_dir }}/scripts/"
      with_items:
      - "chown root:{{ galaxy_user_group }} drmaa_external_runner.py"
      - "chown root:{{ galaxy_user_group }} drmaa_external_killer.py"
      - "chown root:{{ galaxy_user_group }} external_chown_script.py"
      - "chown root:{{ galaxy_user_group }} list_cluster_directories.py"
      changed_when: false

    - name: Set 500 to the permission escalating scripts used for real user setup
      become: true
      become_user: root
      command: "{{ item }} chdir={{ galaxy_lifeportal_data_dir }}/scripts/"
      with_items:
      - chmod 500 drmaa_external_runner.py
      - chmod 500 drmaa_external_killer.py
      - chmod 500 external_chown_script.py
      changed_when: false

  #
  #   # Enable the following variable in the terminal of the remote host (galaxy01.edicloud.no) in order to run
  #   # systemctl --user status galaxy and othe systemctl commands as ec-galaxy user
  #   # XDG_RUNTIME_DIR: "/run/user/{{ galaxy_user_name.uid }}"
  #   # export XDG_RUNTIME_DIR=/run/user/2100096
  #   ## Then as ec-galaxy user run
  #   ## systemctl --user status galaxy
