---

- name: Copy welcome page
  include_tasks: copy_welcome_page.yml
  when: galaxy_manage_static_setup

- name: Change favicon png file put fox icon
  include_tasks: copy_favicon_png.yml
  when: galaxy_manage_static_setup

## Task enbling the users to access their home & project directories on the cluster (Fox)
- name: Copy fox_homes_and_project_access page
  include_tasks: copy_galaxy_fox_access.yml
  when: galaxy_manage_static_setup
  
## 2 Tasks adding the protocols "gxuserhome://" and "gxuserprojects://" for remote files upload galaxy/client/src/utils/upload-payload.js
## Without them throws Error: Invalid url: gxuserprojects://ec73/...
## Needs client rebuild and must be removed after the custom protocols are fixed (Dannon 02.2024)

## Check if file already modified
- name: Verify that upload-payload has been modified in order to avoid unnecessary compilation in the next task
  ansible.builtin.lineinfile:
    path: "{{ galaxy_server_dir }}/client/src/utils/upload-payload.js"
    regex: "gxuserprojects"
    state: absent            # here's the trick
  changed_when: false
  check_mode: true
  register: custom_plugin

## Only run if custom_plugin_found fail
- name: Add two protocols urls to upload remote files
  lineinfile:
    path: "{{ galaxy_server_dir }}/client/src/utils/upload-payload.js"
    backup: yes
    insertafter: "^.*gxuserimport.*$"
    line: "{{ item }}"
  with_items:
   - '    "gxuserhome://",'
   - '    "gxuserprojects://",'
  when: custom_plugin.found != 1

## Tasks related to the modification of the front page (login page with Educloud) ## 
- name: Verify that Login File has been modified for Galaxy-FOX in order to avoid unnecessary compilation in the next task
  ansible.builtin.lineinfile:
    path: "{{ galaxy_server_dir }}/client/src/components/Login/LoginForm.vue"
    regex: "Welcome to the Galaxy-FOX"
    state: absent            # here's the trick
  changed_when: false
  check_mode: true
  register: login_vue_contains_cluster_name

- name: Modify Login vue file
  include_tasks: copy_login_vue.yml
  when: galaxy_manage_static_setup and login_vue_contains_cluster_name != 1

- name: Run make client again after Modify LoginForm vue file or upload-payload file and Modify Makefile
  shell: "source  {{ galaxy_path_prefix }}/srv/galaxy/venv/bin/activate && cd {{ galaxy_path_prefix }}/srv/galaxy/server && npm update caniuse-lite browserslist  && /usr/bin/make client"
  when: login_vue_contains_cluster_name != 1 or custom_plugin_found != 1

  ## The following task is necessary only when the host has no connection to the outside world!!
## Activate 'galaxy_use_tunnel' in the group_vars/galaxy01_educloud.yml
- name: Modify Makefile in galaxy server directory
  lineinfile:
    path: "{{ galaxy_server_dir }}/Makefile"
    backup: yes
    state: present
    insertafter : "^YARN_INSTALL_OPTS"
    line: "{{ item }}"
  with_items:
   - 'HTTPS_PROXY=http://localhost:3128'
   - 'HTTP_PROXY=http://localhost:3128'
  when: galaxy_use_tunnel

## Change the group of the directory containing galaxy services ##
- name: Include chgrp for the directory containing user services
  include_tasks: chgrp_directory_user_systemd_services.yml
  when: not galaxy_systemd_root

## Task copying the scripts for the real user setup
- name: Include copy chown customized scripts
  include_tasks: copy_chown_customized_scripts.yml
  when: galaxy_manage_static_setup
  tags: galaxy_manage_static_setup
  
- name: Insert fox image in managers py
  lineinfile:
          path: "{{ galaxy_server_dir }}/lib/galaxy/authnz/managers.py"
          backup: yes
          insertafter : "^DEFAULT_OIDC_IDP_ICONS"
          line: "    'lifeportalfox': 'https://www.usit.uio.no/bilder/fox_man2.png?vrtx=thumbnail',"

- name: Insert lifeportalfox backend in psa authnz py
  lineinfile:
          path: "{{ galaxy_server_dir }}/lib/galaxy/authnz/psa_authnz.py"
          backup: yes
          insertafter: "^BACKENDS "
          line: "    'lifeportalfox': 'social_core.backends.lifeportal_fox.LifeportalFoxOpenIdConnect',"

- name: Insert  lifeportalfox backend name in psa authnz py
  lineinfile:
          path: "{{ galaxy_server_dir }}/lib/galaxy/authnz/psa_authnz.py"
          backup: yes
          insertafter: "^BACKENDS_NAME"
          line: "    'lifeportalfox': 'lifeportalfox',"

## Job parameters management tasks ##

## Delete 7 lines after line containing JOB_RESOURCE_CONDITIONAL_XML
- name: Edit  JOB_RESOURCE_CONDITIONAL_XML  in jobs_init_py 
  shell: "/usr/bin/sed -i.bak -e '/JOB_RESOURCE_CONDITIONAL_XML = \"\"\"<conditional name=\"__job_resource\"/,+7d' {{ galaxy_path_prefix }}/srv/galaxy/server/lib/galaxy/jobs/__init__.py"

## Set the new values to JOB_RESOURCE_CONDITIONAL_XML
- name: Insert correct order of job parameteres in jobs_init_py 
  lineinfile:
          path: "{{ galaxy_server_dir }}/lib/galaxy/jobs/__init__.py"
          backup: yes
          insertafter: "    DEFAULT_HANDLER_READY_WINDOW_SIZE"
          line: "    JOB_RESOURCE_CONDITIONAL_XML = \"\"\"<conditional name=\"__job_resource\"><param name=\"__job_resource__select\" type=\"select\" label=\"Job Resource Parameters\"><option value=\"yes\">Specify job resource parameters</option><option value=\"no\">Use default job resource parameters</option></param><when value=\"no\"/><when value=\"yes\"/></conditional>\"\"\""



## =========  Temporary task, to be removed in the future =========

# Deactivate the attempt to renew certificate

- name: Insert a hack for missing renewed certificate
  lineinfile:
    path: "{{ galaxy_server_dir }}/lib/galaxy/authnz/managers.py"
    backup: yes
    state: present
    insertafter : "    def refresh_expiring_oidc_tokens_for_provider"
    line: "{{ item }}"
  with_items:
   - '        return'
   - '        log.debug(f" ==== DEACTIVATE refresh_expiring_oidc_tokens ../authnz/managers.py ============= %s ", auth)'
   - '        # Nikolay temporary fix'


### =============== Deactivated tasks =============== ##

## OIDC  - Educloud  configuration tasks ##
# - name: Include lifeportal_fox social_backend
#   include_tasks: copy_lifeportal_fox_backend.yml
#   when: galaxy_manage_static_setup


# ## === This task will be used to install tools  === ##
# - name: Make the lifeportal fox tool directories
#   include_tasks: copy_lifeportal_fox_tool_dirs.yml
#   when: galaxy_manage_static_setup

# Task "Copy LMOD activation scripts" is deactivated now. Can be used in future setups
#- name: Copy LMOD activation scripts
  #include_tasks: copy_lifeportal_fox_lmod_activation_scripts.yml
  #when: galaxy_manage_static_setup
