---

- name: Copy lifeportal fox backend
  copy:
    src: "files/galaxy/oidc_files/{{ item }}"
    dest: "{{ galaxy_oidc_backend_files_target_dir}}/{{ item }}"
  with_items: "{{ galaxy_oidc_backend_files | default([]) }}"
  when:  galaxy_oidc_backend_files is defined
  
- name: Replace CLIENT_ID variable
  ansible.builtin.replace:
    path: "{{ galaxy_root }}/config/oidc_backends_config.xml"
    regexp: 'CLIENT_ID'
    replace: "{{ CLIENT_ID }}"
    
- name: Replace CLIENT_SECRET variable
  ansible.builtin.replace:
    path: "{{ galaxy_root }}/config/oidc_backends_config.xml"
    regexp: 'CLIENT_SECRET'
    replace:  "{{ CLIENT_SECRET }}"
